version: '3'

networks:
  auth_network: 
    driver: bridge

services:
  api_container: 
    build: ./server
    volumes:
      - ./server:/home/node/api
    environment:
      - MONGO_URL=mongo
    depends_on:
      - mongo
    networks:
      - auth_network
    container_name: api_container
    command: npm run start:dev
    ports:
      - "3333:3333"

  mongo:
    image: bitnami/mongodb:latest
    container_name: mongo
    restart: always
    env_file:
      - ./server/.env
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - auth_network

  mongo_test:
    image: bitnami/mongodb:latest
    container_name: mongo_test
    restart: always
    env_file:
      - ./server/.env-testing
    ports: 
      - "27018:27017"
    volumes:
      - mongo_data_test:/data/db
    networks:
      - auth_network 

  web:
    build: ./web
    networks:
      - auth_network 
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - api_container
    container_name: web_app
    ports:
      - "5173:5173" 


volumes: 
  mongo_data:
  mongo_data_test:
