version: '3'

networks:
  auth_network: 
    driver: bridge

services:
  api_container: 
    build: ./server
    volumes:
      - ./server:/home/node/api
    environment:
      - MONGO_URL=mongo
    depends_on:
      - mongo
    networks:
      - auth_network
    container_name: api_container
    command: npm run dev:start
    ports:
      - "3333:3333"

  queue_container:
    build: ./server
    container_name: queue_container
    env_file:
      - ./server/.env
    volumes:
      - ./server:/home/node/api
    depends_on:
      - redis_container
      - mongo 
    networks:
      - auth_network
    command: npm run dev:queue

  redis_container:
    image: bitnami/redis:latest
    container_name: redis_container
    restart: always
    env_file:
      - ./server/.env
    # environment:
    #   - ALLOW_EMPTY_PASSWORD=no
    #   - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes: 
      - redis_data:/bitnami/redis/data
    networks:
      - auth_network 

  mongo:
    image: bitnami/mongodb:latest
    container_name: mongo
    restart: always
    env_file:
      - ./server/.env
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - auth_network

  mongo_test:
    image: bitnami/mongodb:latest
    container_name: mongo_test
    restart: always
    env_file:
      - ./server/.env-testing
    ports: 
      - "27018:27017"
    volumes:
      - mongo_data_test:/data/db
    networks:
      - auth_network 

  web_app:
    container_name: web_app
    build: ./web
    depends_on:
      - api_container
    volumes:
      - web_volume:/var/www/html
    networks:
      - auth_network 

  nginx_container:
    container_name: nginx_container
    build: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - web_volume:/var/www/html
    depends_on:
      - mongo
      - web_app
      - api_container
    networks:
      - auth_network

volumes: 
  mongo_data:
  mongo_data_test:
  web_volume:
  redis_data:
