version: '3'

networks:
  auth_network: 
    driver: bridge

services:
  api: 
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=mongo
    depends_on:
      - mongo
    networks:
      - auth_network
    container_name: api_container
    command: npm run start:dev
    ports:
      - "3333:3333"
  mongo:
    image: bitnami/mongodb:latest
    container_name: mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - auth_network

volumes: 
  mongo_data:
